sudo: required
language: java
jdk:
  - openjdk8
before_install:
install:
  - mvn clean compile
cache:
  directories:
    - $HOME/.m2
script:
  - mvn  sonar:sonar -DskipTests=true -Dsonar.host.url=${SONAR_HOST} -Dsonar.login=${SONAR_TOKEN}
branches:
  only:
    - master
